### ISSUE TITLE
Scroll to top button

### ISSUE THREAD

**Issue by TYPESAFE-RUSTY** [TYPESAFE-RUSTY/contribute-to-this-repo#13]
Scorll to top button will be a great enhancement over the project as the project evolves 

Aim is to implement something similar to #10 .

**Comment by patricksolka** [comment]
Hi! I would like to work on this issue. Does it need to be in vanillaJs and vanillaCSS or am I free to use any framework of choice?

**Comment by TYPESAFE-RUSTY** [comment]
If you are familiar with react / next and want to work on this issue ill assign it to you right away

for styling you can use css np

**Comment by Muhammad-Ahmed-Official** [comment]
Assign me this issue so i can fix it

**Comment by TYPESAFE-RUSTY** [comment]
> Assign me this issue so i can fix it

sure no problem

**Comment by Vinay4912** [comment]
if @Muhammadahmedanis  is not working on this can you assign this to me ?

**Comment by TYPESAFE-RUSTY** [comment]
yeah sure @Vinay4912
